### ISSUE TITLE
Can't Load to S3

### ISSUE THREAD

**Issue by rickwaugh1** [simoneb/grunt-awsebtdeploy#12]
Gets started, then fails on the S3 put:

Running "awsebtdeploy:demo" (awsebtdeploy) task

Warning: "healthPage" is not set, it is recommended to set one

Operating in region "us-west-2"
Checking that application "devtest" exists...OK
Checking that environment with CNAME "devtestx.elasticbeanstalk.com" exists...OK
Uploading source bundle "../dev.zip" to S3 location "devtest/dev.zip"...Warning: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. Use --force to continue.

**Comment by simoneb** [comment]
Have you googled the error? It appears to be related to a wrong AWS region.

**Comment by rickwaugh1** [comment]
Yes, it's a pretty useless error. The other thing that's funny is that, in theory, S3 does not require a region, except it does. Trying a different way to get this done now.

**Comment by simoneb** [comment]
The code should be pretty straightforward, it you can fix it and issue a PR I'm sure it will be appreciated. The AWS package used here is pretty old, maybe it's just a matter of updating to a newer version.
